- name: Get chart jenkins local version 
  shell: helm list -n jenkins | awk -F'-' '$0=$4'| awk '{print $1}'
  ignore_errors: true 
  register: chart_jenkins_local_version
  changed_when: chart_jenkins_local_version.stdout|length == 0

- name: Print chart jenkins local version
  debug:
    msg: "{{ chart_jenkins_local_version.stdout }}"
  when: chart_jenkins_local_version.stdout|length != 0