- name: Add repo vault unseal
  kubernetes.core.helm_repository:
    name: omegion
    repo_url: "https://charts.omegion.dev" 
  notify: Update helm repository

- name: Helm values vault unseal cronjob
  template:
    src: "vault-unseal-values.yaml.j2"
    dest: /root/vault-unseal-values.yaml

- name: Deploy vault unseal cronjob 
  kubernetes.core.helm:
    name: "{{ vault_unseal_helm_name }}"
    chart_ref: "{{ vault_unseal_helm_chart_ref }}"
    chart_version: "{{ vault_unseal_helm_chart_version }}"
    release_namespace: "{{ vault_unseal_helm_namespace }}" 
    values_files: /root/vault-unseal-values.yaml