- name: Checking chart vault unseal version
  include_tasks: check.yaml

- name: Install vault unseal
  include_tasks: install.yaml
  when: chart_vault_unseal_local_version.stdout|length == 0 or chart_vault_unseal_local_version.stdout != vault_unseal_helm_chart_version