- name: Checking Helm version
  include_tasks: check.yaml

- name: Install Helm
  include_tasks: install.yaml
  when: helm_local_version.stdout|length == 0 or helm_local_version.stdout != helm_version
