- name: Check if kubeadm has already run
  stat:
    path: "/etc/kubernetes/pki/ca.key"
  register: kubeadm_ca

- name: Join Kubernetes Control Plane
  shell: |
    {{ hostvars['master_worker_host']['master_join_command'] }} \
    --control-plane \
    --ignore-preflight-errors all
  when: not kubeadm_ca.stat.exists
  register: init_cluster