- name: Checking chart ingress version
  include_tasks: check.yaml

- name: Install ingress nginx
  include_tasks: install.yaml
  when: chart_ingress_local_version.stdout|length == 0 or chart_ingress_local_version.stdout != ingress_helm_chart_version