- name: Create kubernetes secret for docker-hub-credentials
  shell: |  
    kubectl create secret docker-registry docker-hub-credentials \
      --docker-username='{{ docker_hub_username }}' \
      --docker-password='{{ docker_hub_password }}' \
      --docker-email='{{ docker_hub_email }}' \
      --namespace jenkins

- name: Create namespace for sping application
  k8s:
    name: spring-app
    api_version: v1
    kind: Namespace
    state: present

- name: Create kubernetes secret for mysql-credentials
  shell: |  
    kubectl create secret generic mysql-credentials \
      --from-literal=MYSQL_HOST='{{ mysql_host }}' \
      --from-literal=MYSQL_USER='{{ mysql_user }}' \
      --from-literal=MYSQL_PASSWORD='{{ mysql_password }}' \
      --namespace spring-app