- name: Get docker local version 
  shell: docker --version | awk '{print substr($3, 1, length($3)-1)}'
  ignore_errors: true 
  register: docker_local_version
  changed_when: docker_local_version.stdout|length == 0

- name: Print docker local version 
  debug:
    msg: "{{ docker_local_version.stdout }}"
  when: docker_local_version.stdout|length != 0