- name: Add python-pip and python-openshift
  yum:
    name: "{{ item }}"
    state: present
  loop:
    - python-pip
    - python-openshift

- name: Check if kubeadm has already run
  stat:
    path: "/etc/kubernetes/pki/ca.key"
  register: kubeadm_ca

- name: Generate token kubernetes
  shell: kubeadm token generate
  register: kube_master_token

- name: Init Kubernetes cluster
  shell: |
    kubeadm init --kubernetes-version {{ kubernetes_version }} --v=5 \
                --pod-network-cidr {{ network_pod_cidr }} \
                --token {{ kube_master_token.stdout }} \
                --control-plane-endpoint {{ kube_lb_internal }} \
                --apiserver-cert-extra-sans {{ inventory_hostname }},{{ kube_lb_internal }} \
                --upload-certs \
                --ignore-preflight-errors all >> /root/cluster.txt
  when: not kubeadm_ca.stat.exists
  register: init_cluster

- name: Send kubernetes init
  mail:
    host: smtp.gmail.com
    port: 587
    username: "{{ gmail_mail }}"
    password: "{{ gmail_app_password }}"
    to: "{{ gmail_mail }}"
    subject: "FUTURE : Vault Token"
    body: "{{ init_cluster.stdout }}"